// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: bullets.proto

package militaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BulletReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Caliber  float32 `protobuf:"fixed32,2,opt,name=caliber,proto3" json:"caliber,omitempty"`
	Type     string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int32   `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *BulletReq) Reset() {
	*x = BulletReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bullets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulletReq) ProtoMessage() {}

func (x *BulletReq) ProtoReflect() protoreflect.Message {
	mi := &file_bullets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulletReq.ProtoReflect.Descriptor instead.
func (*BulletReq) Descriptor() ([]byte, []int) {
	return file_bullets_proto_rawDescGZIP(), []int{0}
}

func (x *BulletReq) GetCaliber() float32 {
	if x != nil {
		return x.Caliber
	}
	return 0
}

func (x *BulletReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BulletReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Bullet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Caliber  float32 `protobuf:"fixed32,2,opt,name=caliber,proto3" json:"caliber,omitempty"`
	Type     string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int32   `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *Bullet) Reset() {
	*x = Bullet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bullets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bullet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bullet) ProtoMessage() {}

func (x *Bullet) ProtoReflect() protoreflect.Message {
	mi := &file_bullets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bullet.ProtoReflect.Descriptor instead.
func (*Bullet) Descriptor() ([]byte, []int) {
	return file_bullets_proto_rawDescGZIP(), []int{1}
}

func (x *Bullet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bullet) GetCaliber() float32 {
	if x != nil {
		return x.Caliber
	}
	return 0
}

func (x *Bullet) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bullet) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AllBullets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bullets []*Bullet `protobuf:"bytes,1,rep,name=bullets,proto3" json:"bullets,omitempty"`
}

func (x *AllBullets) Reset() {
	*x = AllBullets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bullets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllBullets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllBullets) ProtoMessage() {}

func (x *AllBullets) ProtoReflect() protoreflect.Message {
	mi := &file_bullets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllBullets.ProtoReflect.Descriptor instead.
func (*AllBullets) Descriptor() ([]byte, []int) {
	return file_bullets_proto_rawDescGZIP(), []int{2}
}

func (x *AllBullets) GetBullets() []*Bullet {
	if x != nil {
		return x.Bullets
	}
	return nil
}

var File_bullets_proto protoreflect.FileDescriptor

var file_bullets_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x1a, 0x10, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x09, 0x42, 0x75, 0x6c,
	0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x61, 0x6c, 0x69, 0x62, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x22, 0x62, 0x0a, 0x06, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61,
	0x6c, 0x69, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x61, 0x6c,
	0x69, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0x36, 0x0a, 0x0a, 0x41, 0x6c, 0x6c, 0x42, 0x75, 0x6c, 0x6c, 0x65,
	0x74, 0x73, 0x12, 0x28, 0x0a, 0x07, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x42, 0x75, 0x6c,
	0x6c, 0x65, 0x74, 0x52, 0x07, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x73, 0x32, 0xf2, 0x01, 0x0a,
	0x0d, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x62, 0x75, 0x6c, 0x6c, 0x65,
	0x74, 0x2e, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x74, 0x65,
	0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x2a, 0x0a,
	0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x2e, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74,
	0x2e, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x1a, 0x10, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73,
	0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x10, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x10,
	0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64,
	0x1a, 0x0e, 0x2e, 0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74,
	0x12, 0x2f, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x11, 0x2e, 0x62, 0x75, 0x6c,
	0x6c, 0x65, 0x74, 0x2e, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x62, 0x75, 0x6c, 0x6c, 0x65, 0x74, 0x2e, 0x41, 0x6c, 0x6c, 0x42, 0x75, 0x6c, 0x6c, 0x65, 0x74,
	0x73, 0x42, 0x16, 0x5a, 0x14, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d,
	0x69, 0x6c, 0x69, 0x74, 0x61, 0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_bullets_proto_rawDescOnce sync.Once
	file_bullets_proto_rawDescData = file_bullets_proto_rawDesc
)

func file_bullets_proto_rawDescGZIP() []byte {
	file_bullets_proto_rawDescOnce.Do(func() {
		file_bullets_proto_rawDescData = protoimpl.X.CompressGZIP(file_bullets_proto_rawDescData)
	})
	return file_bullets_proto_rawDescData
}

var file_bullets_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bullets_proto_goTypes = []interface{}{
	(*BulletReq)(nil),  // 0: bullet.BulletReq
	(*Bullet)(nil),     // 1: bullet.Bullet
	(*AllBullets)(nil), // 2: bullet.AllBullets
	(*ById)(nil),       // 3: techniques.ById
	(*Void)(nil),       // 4: techniques.Void
}
var file_bullets_proto_depIdxs = []int32{
	1, // 0: bullet.AllBullets.bullets:type_name -> bullet.Bullet
	0, // 1: bullet.BulletService.Create:input_type -> bullet.BulletReq
	1, // 2: bullet.BulletService.Update:input_type -> bullet.Bullet
	3, // 3: bullet.BulletService.Delete:input_type -> techniques.ById
	3, // 4: bullet.BulletService.Get:input_type -> techniques.ById
	0, // 5: bullet.BulletService.GetAll:input_type -> bullet.BulletReq
	4, // 6: bullet.BulletService.Create:output_type -> techniques.Void
	4, // 7: bullet.BulletService.Update:output_type -> techniques.Void
	4, // 8: bullet.BulletService.Delete:output_type -> techniques.Void
	1, // 9: bullet.BulletService.Get:output_type -> bullet.Bullet
	2, // 10: bullet.BulletService.GetAll:output_type -> bullet.AllBullets
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bullets_proto_init() }
func file_bullets_proto_init() {
	if File_bullets_proto != nil {
		return
	}
	file_techniques_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bullets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulletReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bullets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bullet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bullets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllBullets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bullets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bullets_proto_goTypes,
		DependencyIndexes: file_bullets_proto_depIdxs,
		MessageInfos:      file_bullets_proto_msgTypes,
	}.Build()
	File_bullets_proto = out.File
	file_bullets_proto_rawDesc = nil
	file_bullets_proto_goTypes = nil
	file_bullets_proto_depIdxs = nil
}
