// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: fuels.proto

package militaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FuelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int32  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *FuelReq) Reset() {
	*x = FuelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelReq) ProtoMessage() {}

func (x *FuelReq) ProtoReflect() protoreflect.Message {
	mi := &file_fuels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelReq.ProtoReflect.Descriptor instead.
func (*FuelReq) Descriptor() ([]byte, []int) {
	return file_fuels_proto_rawDescGZIP(), []int{0}
}

func (x *FuelReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FuelReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Fuel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int32  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *Fuel) Reset() {
	*x = Fuel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuels_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fuel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fuel) ProtoMessage() {}

func (x *Fuel) ProtoReflect() protoreflect.Message {
	mi := &file_fuels_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fuel.ProtoReflect.Descriptor instead.
func (*Fuel) Descriptor() ([]byte, []int) {
	return file_fuels_proto_rawDescGZIP(), []int{1}
}

func (x *Fuel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Fuel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Fuel) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AllFuels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fuels []*Fuel `protobuf:"bytes,1,rep,name=fuels,proto3" json:"fuels,omitempty"`
}

func (x *AllFuels) Reset() {
	*x = AllFuels{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuels_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllFuels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllFuels) ProtoMessage() {}

func (x *AllFuels) ProtoReflect() protoreflect.Message {
	mi := &file_fuels_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllFuels.ProtoReflect.Descriptor instead.
func (*AllFuels) Descriptor() ([]byte, []int) {
	return file_fuels_proto_rawDescGZIP(), []int{2}
}

func (x *AllFuels) GetFuels() []*Fuel {
	if x != nil {
		return x.Fuels
	}
	return nil
}

type FuelAddSub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *FuelAddSub) Reset() {
	*x = FuelAddSub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fuels_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FuelAddSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelAddSub) ProtoMessage() {}

func (x *FuelAddSub) ProtoReflect() protoreflect.Message {
	mi := &file_fuels_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelAddSub.ProtoReflect.Descriptor instead.
func (*FuelAddSub) Descriptor() ([]byte, []int) {
	return file_fuels_proto_rawDescGZIP(), []int{3}
}

func (x *FuelAddSub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FuelAddSub) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_fuels_proto protoreflect.FileDescriptor

var file_fuels_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x75, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x66,
	0x75, 0x65, 0x6c, 0x1a, 0x10, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x07, 0x46, 0x75, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x22, 0x46, 0x0a, 0x04, 0x46, 0x75, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x2c, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x46,
	0x75, 0x65, 0x6c, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x66, 0x75, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x66, 0x75, 0x65, 0x6c, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x52,
	0x05, 0x66, 0x75, 0x65, 0x6c, 0x73, 0x22, 0x3c, 0x0a, 0x0a, 0x46, 0x75, 0x65, 0x6c, 0x41, 0x64,
	0x64, 0x53, 0x75, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x32, 0xb2, 0x02, 0x0a, 0x0b, 0x46, 0x75, 0x65, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0d,
	0x2e, 0x66, 0x75, 0x65, 0x6c, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e,
	0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12,
	0x26, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x2e, 0x66, 0x75, 0x65, 0x6c,
	0x2e, 0x46, 0x75, 0x65, 0x6c, 0x1a, 0x10, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x10, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x42,
	0x79, 0x49, 0x64, 0x1a, 0x10, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73,
	0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x10, 0x2e, 0x74,
	0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0a,
	0x2e, 0x66, 0x75, 0x65, 0x6c, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x12, 0x27, 0x0a, 0x06, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x12, 0x0d, 0x2e, 0x66, 0x75, 0x65, 0x6c, 0x2e, 0x46, 0x75, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x66, 0x75, 0x65, 0x6c, 0x2e, 0x41, 0x6c, 0x6c, 0x46, 0x75,
	0x65, 0x6c, 0x73, 0x12, 0x29, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x10, 0x2e, 0x66, 0x75, 0x65,
	0x6c, 0x2e, 0x46, 0x75, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x53, 0x75, 0x62, 0x1a, 0x10, 0x2e, 0x74,
	0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x29,
	0x0a, 0x03, 0x53, 0x75, 0x62, 0x12, 0x10, 0x2e, 0x66, 0x75, 0x65, 0x6c, 0x2e, 0x46, 0x75, 0x65,
	0x6c, 0x41, 0x64, 0x64, 0x53, 0x75, 0x62, 0x1a, 0x10, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x16, 0x5a, 0x14, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x69, 0x6c, 0x69, 0x74, 0x61, 0x72, 0x69, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fuels_proto_rawDescOnce sync.Once
	file_fuels_proto_rawDescData = file_fuels_proto_rawDesc
)

func file_fuels_proto_rawDescGZIP() []byte {
	file_fuels_proto_rawDescOnce.Do(func() {
		file_fuels_proto_rawDescData = protoimpl.X.CompressGZIP(file_fuels_proto_rawDescData)
	})
	return file_fuels_proto_rawDescData
}

var file_fuels_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fuels_proto_goTypes = []interface{}{
	(*FuelReq)(nil),    // 0: fuel.FuelReq
	(*Fuel)(nil),       // 1: fuel.Fuel
	(*AllFuels)(nil),   // 2: fuel.AllFuels
	(*FuelAddSub)(nil), // 3: fuel.FuelAddSub
	(*ById)(nil),       // 4: techniques.ById
	(*Void)(nil),       // 5: techniques.Void
}
var file_fuels_proto_depIdxs = []int32{
	1, // 0: fuel.AllFuels.fuels:type_name -> fuel.Fuel
	0, // 1: fuel.FuelService.Create:input_type -> fuel.FuelReq
	1, // 2: fuel.FuelService.Update:input_type -> fuel.Fuel
	4, // 3: fuel.FuelService.Delete:input_type -> techniques.ById
	4, // 4: fuel.FuelService.Get:input_type -> techniques.ById
	0, // 5: fuel.FuelService.GetAll:input_type -> fuel.FuelReq
	3, // 6: fuel.FuelService.Add:input_type -> fuel.FuelAddSub
	3, // 7: fuel.FuelService.Sub:input_type -> fuel.FuelAddSub
	5, // 8: fuel.FuelService.Create:output_type -> techniques.Void
	5, // 9: fuel.FuelService.Update:output_type -> techniques.Void
	5, // 10: fuel.FuelService.Delete:output_type -> techniques.Void
	1, // 11: fuel.FuelService.Get:output_type -> fuel.Fuel
	2, // 12: fuel.FuelService.GetAll:output_type -> fuel.AllFuels
	5, // 13: fuel.FuelService.Add:output_type -> techniques.Void
	5, // 14: fuel.FuelService.Sub:output_type -> techniques.Void
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fuels_proto_init() }
func file_fuels_proto_init() {
	if File_fuels_proto != nil {
		return
	}
	file_techniques_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_fuels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuels_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fuel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuels_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllFuels); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fuels_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FuelAddSub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fuels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fuels_proto_goTypes,
		DependencyIndexes: file_fuels_proto_depIdxs,
		MessageInfos:      file_fuels_proto_msgTypes,
	}.Build()
	File_fuels_proto = out.File
	file_fuels_proto_rawDesc = nil
	file_fuels_proto_goTypes = nil
	file_fuels_proto_depIdxs = nil
}
