// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: techniques.proto

package militaries

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ById) Reset() {
	*x = ById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_techniques_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ById) ProtoMessage() {}

func (x *ById) ProtoReflect() protoreflect.Message {
	mi := &file_techniques_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ById.ProtoReflect.Descriptor instead.
func (*ById) Descriptor() ([]byte, []int) {
	return file_techniques_proto_rawDescGZIP(), []int{0}
}

func (x *ById) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Void struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Void) Reset() {
	*x = Void{}
	if protoimpl.UnsafeEnabled {
		mi := &file_techniques_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_techniques_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_techniques_proto_rawDescGZIP(), []int{1}
}

type TechniqueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model    string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int32  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *TechniqueReq) Reset() {
	*x = TechniqueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_techniques_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TechniqueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechniqueReq) ProtoMessage() {}

func (x *TechniqueReq) ProtoReflect() protoreflect.Message {
	mi := &file_techniques_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechniqueReq.ProtoReflect.Descriptor instead.
func (*TechniqueReq) Descriptor() ([]byte, []int) {
	return file_techniques_proto_rawDescGZIP(), []int{2}
}

func (x *TechniqueReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TechniqueReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TechniqueReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Technique struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model    string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Quantity int32  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *Technique) Reset() {
	*x = Technique{}
	if protoimpl.UnsafeEnabled {
		mi := &file_techniques_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Technique) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Technique) ProtoMessage() {}

func (x *Technique) ProtoReflect() protoreflect.Message {
	mi := &file_techniques_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Technique.ProtoReflect.Descriptor instead.
func (*Technique) Descriptor() ([]byte, []int) {
	return file_techniques_proto_rawDescGZIP(), []int{3}
}

func (x *Technique) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Technique) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Technique) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Technique) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AllTechnique struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Techniques []*Technique `protobuf:"bytes,1,rep,name=techniques,proto3" json:"techniques,omitempty"`
}

func (x *AllTechnique) Reset() {
	*x = AllTechnique{}
	if protoimpl.UnsafeEnabled {
		mi := &file_techniques_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllTechnique) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTechnique) ProtoMessage() {}

func (x *AllTechnique) ProtoReflect() protoreflect.Message {
	mi := &file_techniques_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTechnique.ProtoReflect.Descriptor instead.
func (*AllTechnique) Descriptor() ([]byte, []int) {
	return file_techniques_proto_rawDescGZIP(), []int{4}
}

func (x *AllTechnique) GetTechniques() []*Technique {
	if x != nil {
		return x.Techniques
	}
	return nil
}

type TechniqueAddSub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *TechniqueAddSub) Reset() {
	*x = TechniqueAddSub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_techniques_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TechniqueAddSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechniqueAddSub) ProtoMessage() {}

func (x *TechniqueAddSub) ProtoReflect() protoreflect.Message {
	mi := &file_techniques_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechniqueAddSub.ProtoReflect.Descriptor instead.
func (*TechniqueAddSub) Descriptor() ([]byte, []int) {
	return file_techniques_proto_rawDescGZIP(), []int{5}
}

func (x *TechniqueAddSub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TechniqueAddSub) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_techniques_proto protoreflect.FileDescriptor

var file_techniques_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x22, 0x16,
	0x0a, 0x04, 0x42, 0x79, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x06, 0x0a, 0x04, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x54,
	0x0a, 0x0c, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x22, 0x61, 0x0a, 0x09, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x45, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x54, 0x65,
	0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x74, 0x65, 0x63, 0x68, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x65,
	0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x52, 0x0a, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x22, 0x41,
	0x0a, 0x0f, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x41, 0x64, 0x64, 0x53, 0x75,
	0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x32, 0x83, 0x03, 0x0a, 0x10, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x54, 0x65,
	0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x74, 0x65, 0x63,
	0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x1a, 0x10, 0x2e,
	0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12,
	0x2c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x74, 0x65, 0x63, 0x68,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x10, 0x2e, 0x74, 0x65,
	0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x12, 0x2e, 0x0a,
	0x03, 0x47, 0x65, 0x74, 0x12, 0x10, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x15, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x3c, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x18, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x41,
	0x6c, 0x6c, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x34, 0x0a, 0x03, 0x41,
	0x64, 0x64, 0x12, 0x1b, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e,
	0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x41, 0x64, 0x64, 0x53, 0x75, 0x62, 0x1a,
	0x10, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69,
	0x64, 0x12, 0x34, 0x0a, 0x03, 0x53, 0x75, 0x62, 0x12, 0x1b, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x41,
	0x64, 0x64, 0x53, 0x75, 0x62, 0x1a, 0x10, 0x2e, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x42, 0x16, 0x5a, 0x14, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x69, 0x6c, 0x69, 0x74, 0x61, 0x72, 0x69, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_techniques_proto_rawDescOnce sync.Once
	file_techniques_proto_rawDescData = file_techniques_proto_rawDesc
)

func file_techniques_proto_rawDescGZIP() []byte {
	file_techniques_proto_rawDescOnce.Do(func() {
		file_techniques_proto_rawDescData = protoimpl.X.CompressGZIP(file_techniques_proto_rawDescData)
	})
	return file_techniques_proto_rawDescData
}

var file_techniques_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_techniques_proto_goTypes = []interface{}{
	(*ById)(nil),            // 0: techniques.ById
	(*Void)(nil),            // 1: techniques.Void
	(*TechniqueReq)(nil),    // 2: techniques.TechniqueReq
	(*Technique)(nil),       // 3: techniques.Technique
	(*AllTechnique)(nil),    // 4: techniques.AllTechnique
	(*TechniqueAddSub)(nil), // 5: techniques.TechniqueAddSub
}
var file_techniques_proto_depIdxs = []int32{
	3, // 0: techniques.AllTechnique.techniques:type_name -> techniques.Technique
	2, // 1: techniques.TechniqueService.Create:input_type -> techniques.TechniqueReq
	3, // 2: techniques.TechniqueService.Update:input_type -> techniques.Technique
	0, // 3: techniques.TechniqueService.Delete:input_type -> techniques.ById
	0, // 4: techniques.TechniqueService.Get:input_type -> techniques.ById
	2, // 5: techniques.TechniqueService.GetAll:input_type -> techniques.TechniqueReq
	5, // 6: techniques.TechniqueService.Add:input_type -> techniques.TechniqueAddSub
	5, // 7: techniques.TechniqueService.Sub:input_type -> techniques.TechniqueAddSub
	1, // 8: techniques.TechniqueService.Create:output_type -> techniques.Void
	1, // 9: techniques.TechniqueService.Update:output_type -> techniques.Void
	1, // 10: techniques.TechniqueService.Delete:output_type -> techniques.Void
	3, // 11: techniques.TechniqueService.Get:output_type -> techniques.Technique
	4, // 12: techniques.TechniqueService.GetAll:output_type -> techniques.AllTechnique
	1, // 13: techniques.TechniqueService.Add:output_type -> techniques.Void
	1, // 14: techniques.TechniqueService.Sub:output_type -> techniques.Void
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_techniques_proto_init() }
func file_techniques_proto_init() {
	if File_techniques_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_techniques_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_techniques_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Void); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_techniques_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TechniqueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_techniques_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Technique); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_techniques_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllTechnique); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_techniques_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TechniqueAddSub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_techniques_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_techniques_proto_goTypes,
		DependencyIndexes: file_techniques_proto_depIdxs,
		MessageInfos:      file_techniques_proto_msgTypes,
	}.Build()
	File_techniques_proto = out.File
	file_techniques_proto_rawDesc = nil
	file_techniques_proto_goTypes = nil
	file_techniques_proto_depIdxs = nil
}
