// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ai/chat": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "CHat with AI",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "CHAT",
                "parameters": [
                    {
                        "description": "Bullet Request",
                        "name": "BulletReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ai.AiCHat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while creating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ai/gethistory/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "CHat with AI",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI"
                ],
                "summary": "GetHistory",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while creating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/bullet/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new bullet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bullet"
                ],
                "summary": "Create Bullet",
                "parameters": [
                    {
                        "description": "Bullet Request",
                        "name": "BulletReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/militaries.BulletReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while creating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/bullet/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing bullet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bullet"
                ],
                "summary": "Delete Bullet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bullet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while deleting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
=======
        "/bullet/get/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get an existing bullet by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bullet"
                ],
                "summary": "Get Bullet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bullet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Successful",
                        "schema": {
                            "$ref": "#/definitions/militaries.Bullet"
                        }
                    },
                    "401": {
                        "description": "Error while getting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
>>>>>>> bef80a0 (add auth)
        "/bullet/getall": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all bullets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bullet"
                ],
                "summary": "Get All Bullets",
                "parameters": [
                    {
                        "type": "number",
                        "name": "caliber",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "quantity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get All Successful",
                        "schema": {
                            "$ref": "#/definitions/militaries.AllBullets"
                        }
                    },
                    "401": {
                        "description": "Error while getting all",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/bullet/getbyid/{id}": {
            "get": {
                "description": "Get an existing bullet by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bullet"
                ],
                "summary": "Get Bullet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bullet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Successful",
                        "schema": {
                            "$ref": "#/definitions/militaries.Bullet"
                        }
                    },
                    "401": {
                        "description": "Error while getting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/bullet/update/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing bullet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bullet"
                ],
                "summary": "Update Bullet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bullet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Bullet",
                        "name": "Bullet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/militaries.Bullet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while updating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/commander/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new commander",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Commander"
                ],
                "summary": "Create Commander",
                "parameters": [
                    {
                        "description": "Commander Request",
                        "name": "CommanderReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/soldiers.CreateCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while creating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/commander/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing commander",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Commander"
                ],
                "summary": "Delete Commander",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Commander ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while deleting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/commander/get/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get an existing commander by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Commander"
                ],
                "summary": "Get Commander",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Commander ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Successful",
                        "schema": {
                            "$ref": "#/definitions/soldiers.Commander"
                        }
                    },
                    "401": {
                        "description": "Error while getting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/commander/getall": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all commanders",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Commander"
                ],
                "summary": "Get All Commanders",
                "parameters": [
                    {
                        "type": "string",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get All Successful",
                        "schema": {
                            "$ref": "#/definitions/soldiers.AllCommanders"
                        }
                    },
                    "401": {
                        "description": "Error while getting all",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/commander/update/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing commander",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Commander"
                ],
                "summary": "Update Commander",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Commander ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Commander",
                        "name": "Commander",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/soldiers.Commander"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while updating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/department/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new department",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Create Department",
                "parameters": [
                    {
                        "description": "Department",
                        "name": "Department",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/soldiers.CreateDeportment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while creating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/department/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing department",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Delete Department",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Department ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while deleting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/department/get/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get an existing department by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Get Department",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Department ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Successful",
                        "schema": {
                            "$ref": "#/definitions/soldiers.Department"
                        }
                    },
                    "401": {
                        "description": "Error while getting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/department/getall": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all departments",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Get All Departments",
                "parameters": [
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get All Successful",
                        "schema": {
                            "$ref": "#/definitions/soldiers.AllDepartments"
                        }
                    },
                    "401": {
                        "description": "Error while getting all",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/department/update/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing department",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Department"
                ],
                "summary": "Update Department",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Department ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Department",
                        "name": "Department",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/soldiers.Department"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while updating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fuel/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new fuel entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fuel"
                ],
                "summary": "Create Fuel",
                "parameters": [
                    {
                        "description": "Fuel Request",
                        "name": "FuelReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/militaries.FuelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error while creating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fuel/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing fuel entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fuel"
                ],
                "summary": "Delete Fuel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fuel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error while deleting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
=======
        "/fuel/get/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get an existing fuel entry by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fuel"
                ],
                "summary": "Get Fuel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fuel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Successful",
                        "schema": {
                            "$ref": "#/definitions/militaries.Fuel"
                        }
                    },
                    "400": {
                        "description": "Error while getting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
>>>>>>> bef80a0 (add auth)
        "/fuel/getall": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all fuel entries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fuel"
                ],
                "summary": "Get All Fuels",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "quantity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get All Successful",
                        "schema": {
                            "$ref": "#/definitions/militaries.AllFuels"
                        }
                    },
                    "400": {
                        "description": "Error while getting all",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fuel/getbyid/{id}": {
            "get": {
                "description": "Get an existing fuel entry by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fuel"
                ],
                "summary": "Get Fuel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fuel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Successful",
                        "schema": {
                            "$ref": "#/definitions/militaries.Fuel"
                        }
                    },
                    "400": {
                        "description": "Error while getting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fuel/update/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing fuel entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Fuel"
                ],
                "summary": "Update Fuel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Fuel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fuel",
                        "name": "Fuel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/militaries.Fuel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error while updating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/group/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "Create Group",
                "parameters": [
                    {
                        "description": "Group Request",
                        "name": "GroupReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/soldiers.GroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while creating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/group/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "Delete Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while deleting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/group/get/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get an existing group by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "Get Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Successful",
                        "schema": {
                            "$ref": "#/definitions/soldiers.Group"
                        }
                    },
                    "401": {
                        "description": "Error while getting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/group/getall": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all groups",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "Get All Groups",
                "parameters": [
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get All Successful",
                        "schema": {
                            "$ref": "#/definitions/soldiers.AllGroups"
                        }
                    },
                    "401": {
                        "description": "Error while getting all",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/group/update/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Group"
                ],
                "summary": "Update Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Group ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Group",
                        "name": "Group",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/soldiers.Group"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while updating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/soldier/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new soldier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Soldier"
                ],
                "summary": "Create Soldier",
                "parameters": [
                    {
                        "description": "Soldier Request",
                        "name": "SoldierReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/soldiers.CreateSoldier"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while creating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/soldier/dashbord": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all Dashbord",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashbord"
                ],
                "summary": "Get All Dashbord",
                "parameters": [
                    {
                        "type": "string",
                        "name": "date_of_birth",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "group_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "join_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "phone_number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get All Successful",
                        "schema": {
                            "$ref": "#/definitions/soldiers.AllSoldiers"
                        }
                    },
                    "401": {
                        "description": "Error while getting all",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/soldier/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing soldier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Soldier"
                ],
                "summary": "Delete Soldier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Soldier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while deleting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/soldier/get/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get an existing soldier by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Soldier"
                ],
                "summary": "Get Soldier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Soldier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Successful",
                        "schema": {
                            "$ref": "#/definitions/soldiers.Soldier"
                        }
                    },
                    "401": {
                        "description": "Error while getting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/soldier/getall": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all soldiers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Soldier"
                ],
                "summary": "Get All Soldiers",
                "parameters": [
                    {
                        "type": "string",
                        "name": "age",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get All Successful",
                        "schema": {
                            "$ref": "#/definitions/soldiers.AllSoldiers"
                        }
                    },
                    "401": {
                        "description": "Error while getting all",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/soldier/update/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing soldier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Soldier"
                ],
                "summary": "Update Soldier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Soldier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Soldier",
                        "name": "Soldier",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/soldiers.Soldier"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while updating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/soldier/usebullet": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Record the use of bullets by a soldier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Soldier"
                ],
                "summary": "Use Bullet",
                "parameters": [
                    {
                        "description": "Use Bullet",
                        "name": "UseB",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/soldiers.UseB"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Use Bullet Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while using bullet",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/soldier/usefuel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Record the use of fuel by a soldier",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Soldier"
                ],
                "summary": "Use Fuel",
                "parameters": [
                    {
                        "description": "Use Fuel",
                        "name": "UseF",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/soldiers.UseF"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Use Fuel Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Error while using fuel",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/technique/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new technique entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Technique"
                ],
                "summary": "Create Technique",
                "parameters": [
                    {
                        "description": "Technique Request",
                        "name": "TechniqueReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/militaries.TechniqueReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Create Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error while creating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/technique/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an existing technique entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Technique"
                ],
                "summary": "Delete Technique",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Technique ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error while deleting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
<<<<<<< HEAD
=======
        "/technique/get/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get an existing technique entry by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Technique"
                ],
                "summary": "Get Technique",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Technique ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Successful",
                        "schema": {
                            "$ref": "#/definitions/militaries.Technique"
                        }
                    },
                    "400": {
                        "description": "Error while getting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
>>>>>>> bef80a0 (add auth)
        "/technique/getall": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all technique entries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Technique"
                ],
                "summary": "Get All Techniques",
                "parameters": [
                    {
                        "type": "string",
                        "name": "model",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "quantity",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get All Successful",
                        "schema": {
                            "$ref": "#/definitions/militaries.AllTechnique"
                        }
                    },
                    "400": {
                        "description": "Error while getting all",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/technique/getbyid/{id}": {
            "get": {
                "description": "Get an existing technique entry by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Technique"
                ],
                "summary": "Get Technique",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Technique ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get Successful",
                        "schema": {
                            "$ref": "#/definitions/militaries.Technique"
                        }
                    },
                    "400": {
                        "description": "Error while getting",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/technique/update/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing technique entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Technique"
                ],
                "summary": "Update Technique",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Technique ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Technique",
                        "name": "Technique",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/militaries.Technique"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update Successful",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Error while updating",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ai.AiCHat": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "militaries.AllBullets": {
            "type": "object",
            "properties": {
                "bullets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/militaries.Bullet"
                    }
                }
            }
        },
        "militaries.AllFuels": {
            "type": "object",
            "properties": {
                "fuels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/militaries.Fuel"
                    }
                }
            }
        },
        "militaries.AllTechnique": {
            "type": "object",
            "properties": {
                "techniques": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/militaries.Technique"
                    }
                }
            }
        },
        "militaries.Bullet": {
            "type": "object",
            "properties": {
                "caliber": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "militaries.BulletReq": {
            "type": "object",
            "properties": {
                "caliber": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "militaries.Fuel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "militaries.FuelReq": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "militaries.Technique": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "militaries.TechniqueReq": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "soldiers.AllCommanders": {
            "type": "object",
            "properties": {
                "commanders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/soldiers.Commander"
                    }
                }
            }
        },
        "soldiers.AllDepartments": {
            "type": "object",
            "properties": {
                "departments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/soldiers.Department"
                    }
                }
            }
        },
        "soldiers.AllGroups": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/soldiers.Group"
                    }
                }
            }
        },
        "soldiers.AllSoldiers": {
            "type": "object",
            "properties": {
                "soldiers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/soldiers.Soldier"
                    }
                }
            }
        },
        "soldiers.Commander": {
            "type": "object",
            "properties": {
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                }
            }
        },
        "soldiers.CreateCommand": {
            "type": "object",
            "properties": {
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "soldiers.CreateDeportment": {
            "type": "object",
            "properties": {
                "commanders_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "soldiers.CreateSoldier": {
            "type": "object",
            "properties": {
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "group": {
                    "$ref": "#/definitions/soldiers.Group"
                },
                "join_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "soldiers.Department": {
            "type": "object",
            "properties": {
                "commander": {
                    "$ref": "#/definitions/soldiers.Commander"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "soldiers.Group": {
            "type": "object",
            "properties": {
                "department": {
                    "$ref": "#/definitions/soldiers.Department"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "soldiers.GroupReq": {
            "type": "object",
            "properties": {
                "department_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "soldiers.Soldier": {
            "type": "object",
            "properties": {
                "date_of_birth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "group": {
                    "$ref": "#/definitions/soldiers.Group"
                },
                "id": {
                    "type": "string"
                },
                "join_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                }
            }
        },
        "soldiers.UseB": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "quantity_big_weapon": {
                    "type": "integer"
                },
                "quantity_weapon": {
                    "type": "integer"
                },
                "soldier_id": {
                    "type": "string"
                }
            }
        },
        "soldiers.UseF": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "diesel": {
                    "type": "integer"
                },
                "petrol": {
                    "type": "integer"
                },
                "soldier_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authourization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "Millitary service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
